### ISSUE TITLE
Kan geen milkshake bestellen

### ISSUE THREAD

**Issue by Knoop** [joostrijneveld/eetFestijn#13]
Suggestie: neem een menu mee bij de fest.

**Comment by joostrijneveld** [comment]
Drinks and icecreams are not on the takeaway menu's, but they might be listed on posters.. Legible photos are appreciated!

**Comment by jjmartens** [comment]
Maybe it's an idea to add an openfield, so i can order my "Broodje Bamischijf".

**Comment by joostrijneveld** [comment]
An open text field would complicate things extremely, as that would involve managing `Item` instances dynamically instead of at migration-time. I've decided against jumping those hoops.
